# Generated by Django 5.2.4 on 2025-07-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='phone_no',
            field=models.CharField(),
        ),
    ]
