# Generated by Django 5.2.4 on 2025-07-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_details_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='usertype',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=50),
        ),
    ]
