# Generated by Django 5.2.4 on 2025-07-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_details_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
