# Generated by Django 5.2.4 on 2025-07-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
